version: 2

sources:
  - name: parquet_input
    meta:
      external_location: "read_parquet('{{ env_var('INPUT_FILES_PATH') }}/{name}.parquet')"
    tables:
      - name: channels
      - name: customers
      - name: products
      - name: resellers
      - name: main
      - name: resellers_type1
      - name: resellers_type2




